### ISSUE TITLE
Fully-convective stars

### ISSUE THREAD

**Issue by bmorris3** [RuthAngus/stardate#2]
Hi @RuthAngus!

I'm interested in using `stardate` for a project I'm working on with fully-convective stars. I see in your paper's Discussion section that these stars perhaps shouldn't trusted with `stardate`. I'm wondering if you could elaborate a bit on what circumstances need to be met to trust `stardate` ages for fully-convective stars?

Thanks so much 😄

**Comment by RuthAngus** [comment]
Hi Brett! 

The oldest M dwarfs with rotation periods are in the Praesepe cluster and are only ~500 million years old. So, we don't really know how the rotation periods of these stars evolve past this. stardate models FGK and early M stars with a deterministic gyrochronology model, but the ages of stars redder than B-V = 1.25 (based on Praesepe observations -- see the attached plots) can't be determined from their rotation periods, at least at Praesepe age. In other words, using a rotation period won't help you constrain the age of a late M if you're using stardate. Does that answer your question?
<img width="812" alt="douglas_etal_2017" src="https://user-images.githubusercontent.com/2834161/53981634-ca681880-40c7-11e9-8e58-1d6f933c22c5.png">
<img width="681" alt="rebull_etal_2017" src="https://user-images.githubusercontent.com/2834161/53981648-d358ea00-40c7-11e9-9761-293c822a6582.png">

**Comment by bmorris3** [comment]
Yes perfectly. Thanks @RuthAngus :)
